services:
  - type: web
    name: Quant
    env: go
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    envGroup: Quant
    envVars:
      - key: COPY_AMOUNT_USD
        value: "20"  # Overrides the group's value specifically for this service